#!/bin/bash
RESOURCE_GROUP_NAME="$1"
IMAGE_NAME="$2"
IMAGE_TAG="$3"
REGISTRY_NAME="$4"
DOCKERFILE_CONTEXT="$5"

az acr build --resource-group $RESOURCE_GROUP_NAME --registry $REGISTRY_NAME --image $IMAGE_NAME:$IMAGE_TAG $DOCKERFILE_CONTEXT